package stratego;

import java.awt.Font;

public class MiPerfil extends javax.swing.JFrame {
    Login login;
    ControladorLogin controladorlogin=new ControladorLogin();
    
    public MiPerfil(Login login, ControladorLogin controladorlogin) {
        initComponents();
        setLocationRelativeTo(null);
        Font Arial = new Font("Arial", Font.BOLD, 18);
        this.login=login;
        this.controladorlogin=controladorlogin;
        lblUsuarioLogeado.setText(controladorlogin.UsuarioLogeado);
        lblpuntosusuario.setText(String.valueOf(controladorlogin.buscarUsuario(controladorlogin.UsuarioLogeado).getPuntos()));
        lblvecesjugadasheroe.setText(String.valueOf(controladorlogin.buscarUsuario(controladorlogin.UsuarioLogeado).getVecesJugadasHeroes()));
        lblvecesjugadasvillano.setText(String.valueOf(controladorlogin.buscarUsuario(controladorlogin.UsuarioLogeado).getVecesJugadasVillanos()));
        talogs.setEditable(false);
        
        talogs.setFont(Arial);
        if(controladorlogin.logs.equals("")){
            talogs.setText("Aun no se ha registrado ninguna partida.");
        }else{
        talogs.setText(controladorlogin.logs);
            
        }
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCambiarPassword = new javax.swing.JButton();
        btnEliminarMiCuenta = new javax.swing.JButton();
        btnRegresarAMenuPrincipal = new javax.swing.JButton();
        lblUsuarioLogeado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblpuntosusuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblvecesjugadasheroe = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblvecesjugadasvillano = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        talogs = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCambiarPassword.setBackground(new java.awt.Color(51, 51, 255));
        btnCambiarPassword.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnCambiarPassword.setText("CAMBIAR MI PASSWORD");
        btnCambiarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(btnCambiarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 60, -1, 77));

        btnEliminarMiCuenta.setBackground(new java.awt.Color(51, 51, 255));
        btnEliminarMiCuenta.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnEliminarMiCuenta.setText("ELIMINAR MI CUENTA");
        btnEliminarMiCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMiCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarMiCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 170, 344, 69));

        btnRegresarAMenuPrincipal.setBackground(new java.awt.Color(255, 51, 51));
        btnRegresarAMenuPrincipal.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnRegresarAMenuPrincipal.setText("REGRESAR AL MENU PRINCIPAL");
        btnRegresarAMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarAMenuPrincipalActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresarAMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 475, 344, 63));

        lblUsuarioLogeado.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblUsuarioLogeado.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblUsuarioLogeado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 230, 50));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MI PERFIL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 7, 243, 43));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Puntos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        lblpuntosusuario.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblpuntosusuario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblpuntosusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 47, 45));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Veces jugadas como heroes:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 159, -1, -1));

        lblvecesjugadasheroe.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblvecesjugadasheroe.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblvecesjugadasheroe, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 47, 45));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Logs de las partidas jugadas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 350, -1));

        lblvecesjugadasvillano.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblvecesjugadasvillano.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblvecesjugadasvillano, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 47, 45));

        talogs.setColumns(20);
        talogs.setRows(5);
        jScrollPane1.setViewportView(talogs);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 680, 140));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Veces jugadas como villanos:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarAMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarAMenuPrincipalActionPerformed
        MenuPrincipal menuprincipal=new MenuPrincipal(login, controladorlogin);
        menuprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarAMenuPrincipalActionPerformed

    private void btnCambiarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarPasswordActionPerformed
    CambiarPassword cambiarpassword= new CambiarPassword(login, controladorlogin);
        cambiarpassword.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCambiarPasswordActionPerformed

    private void btnEliminarMiCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMiCuentaActionPerformed
        EliminarMiCuenta eliminarmicuenta = new EliminarMiCuenta(login, controladorlogin);
        eliminarmicuenta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEliminarMiCuentaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarPassword;
    private javax.swing.JButton btnEliminarMiCuenta;
    private javax.swing.JButton btnRegresarAMenuPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsuarioLogeado;
    private javax.swing.JLabel lblpuntosusuario;
    private javax.swing.JLabel lblvecesjugadasheroe;
    private javax.swing.JLabel lblvecesjugadasvillano;
    private javax.swing.JTextArea talogs;
    // End of variables declaration//GEN-END:variables
}
