package stratego;

import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class VentanaRegistrarse extends javax.swing.JFrame {
    
    Login login;
    ControladorLogin controladorlogin;
    /**
     * Creates new form VentanaRegistrarse
     */
    public VentanaRegistrarse(Login login, ControladorLogin controladorlogin) {
        initComponents();
        setLocationRelativeTo(this);
        
        this.login=login;
        this.controladorlogin=controladorlogin;
        
    }

    private VentanaRegistrarse() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuarioRegistro = new javax.swing.JTextField();
        crearCuentaButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtContraRegistro = new javax.swing.JPasswordField();
        btnRegresarALogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));
        jPanel1.add(txtUsuarioRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 244, 36));

        crearCuentaButton.setBackground(new java.awt.Color(0, 102, 255));
        crearCuentaButton.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        crearCuentaButton.setForeground(new java.awt.Color(255, 255, 255));
        crearCuentaButton.setText("Crear Player");
        crearCuentaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCuentaButtonActionPerformed(evt);
            }
        });
        jPanel1.add(crearCuentaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 210, 50));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        txtContraRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(txtContraRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 244, 37));

        btnRegresarALogin.setBackground(new java.awt.Color(204, 0, 0));
        btnRegresarALogin.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnRegresarALogin.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarALogin.setText("Volver");
        btnRegresarALogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarALoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresarALogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 139, 50));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REGISTRO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 273, 45));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/T/registro.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 760, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearCuentaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCuentaButtonActionPerformed
        //Iniciar creacion de usuario
        String user = txtUsuarioRegistro.getText();
        String contrasena = new String(txtContraRegistro.getPassword());
        int puntos=0;
        int vecesJugadasHeroes=0;
        int vecesJugadasVillanos=0;
        Usuario usuario = new Usuario(user,contrasena,puntos,vecesJugadasHeroes,vecesJugadasVillanos);
        if(txtContraRegistro.getPassword().length!=5){
            JOptionPane.showMessageDialog(null, "La contraseña debe de ser de exactamente 5 caracteres.");
        }else{
        if(txtUsuarioRegistro.getText().isEmpty() || txtContraRegistro.getPassword().length<1){
            JOptionPane.showMessageDialog(null, "Ingrese usuario y contraseña.");
        }else{
            //Guardar usuario
        boolean respuesta = login.getControlador().agregarUsuario(usuario);
         if(respuesta == true) {
             controladorlogin.totalUsuariosActivos++;
             controladorlogin.totalUsuariosHistoricos++;
             JOptionPane.showMessageDialog(null, "Se ha registrado correctamente.");
         }else{
             JOptionPane.showMessageDialog(null, "El usuario ya existe.");
         }
        }
        }
        


    }//GEN-LAST:event_crearCuentaButtonActionPerformed

    private void btnRegresarALoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarALoginActionPerformed
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarALoginActionPerformed

    private void txtContraRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresarALogin;
    private javax.swing.JButton crearCuentaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtContraRegistro;
    private javax.swing.JTextField txtUsuarioRegistro;
    // End of variables declaration//GEN-END:variables
}
